version: '2.4'
services:
    fastapi-app:
        build: .
        command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
